#ifndef TMEP_SETTINGS_GLSL
#define TMEP_SETTINGS_GLSL

#define WATER_RIPPLE_LAYERS 3
#define WATER_PARALLAX_ENABLED 1
#define WATER_TRILINEAR 1
#define WATER_MEASURED_DEPTH 1
#define WATER_BED_CAUSTICS_ENABLED 1
#define FOLIAGE_SWAY_ENABLED 1
#define WATER_VERTEX_WAVES 1
#define LIGHTING_STYLE 0
#define EXPERIMENTAL_SHADOWS_BROKEN_DO_NOT_ENABLE 0

#endif
